---
title: "test"
author: "Christoper Chan"
date: "`r format(Sys.time(), '%H:%M %d %B %Y')`"
output: github_document
---
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(here)
```

This correctly makes a md file in the reports.
```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r make and move report}
make_md <- function(input_name, output_name) {
  # Moves the knitted md and supporting images from the notebooks dir to reports
  # dir. 
  # 
  # Args:
  #   input_name: The name of the knitted md. Typically same as the Rmd title.
  #   output_name: A new name for the md in the reports dir.
  #
  # Output: A new md in the reports dir. 
  file.rename(from = here('notebooks', input_name), 
              to = here('reports', output_name))
  
  file.copy(from = list.files(pattern = '*files'), 
            to = here('reports'), recursive = TRUE)
}
```


```{r}
make_md('test.md', 'test.md')
```
  file.rename(here('notebooks', paste(input_name, 'files', sep = '_')),
              here('reports', paste(output_name, 'files', sep = '_')),
              recursive = TRUE)

TO DO:

- Make md render graphs properly
  * [This](https://deanattali.com/blog/ezknitr-package/) might fix my problems
  * Helpful links:
    - https://community.rstudio.com/t/is-it-possible-to-save-the-html-output-in-a-directory-which-is-not-the-one-where-the-rmd-file-resides/3588
    - https://github.com/rstudio/rmarkdown/issues/587
    - https://github.com/yihui/knitr/issues/913
    - https://gist.github.com/jennybc/362f52446fe1ebc4c49f




```{r}
df <- data.frame(X = 1:5, Y = 1:5)
a <- ggplot(df, aes(X, Y)) +
  geom_point()
print(a)
```

```{r}
print('hello world')
```
```{r}

# knit: (function(input_file, encoding) {
#        rmarkdown::render(input_file, 
#                         encoding = encoding, 
#                         output_file=file.path(dirname(input_file), 'test_dir', 'analysis.md'))
#                         })

```




